### ISSUE TITLE
the model issue 

### ISSUE THREAD

**Issue by liquidzym** [Jonathhhan/ofStableDiffusionExample#2]
sorry i've  been try to download the model from https://github.com/leejet/stable-diffusion.cpp/issues/28#issuecomment-1694486320
but it's stable-diffusion-nano-2-1-ggml-f32.bin, the example using the f16.bin does it?

**Comment by Jonathhhan** [comment]
@liquidzym you are right (I converted it myself to f16). Changed the example, so that it works with the `ggml` model from the link.

**Comment by liquidzym** [comment]
ok, i see,thank you
